# Use lightweight Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files into container
COPY . /app

# Install required library
RUN pip install --no-cache-dir cryptography

# Security: run as non-root user
RUN useradd -m secureuser
USER secureuser

# Run application
CMD ["python", "python-simulation-for-data-security.py"]
